[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python -m playwright install-deps && python -m playwright install chromium"

[deploy]
startCommand = "python sports_discord_bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"