[build]
builder = "NIXPACKS"
buildCommand = "pip install -r discord/requirements.txt"

[deploy]
startCommand = "cd discord && python bot_structure.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"