[build]
builder = "nixpacks"

[deploy]
startCommand = "python odds_mcp_v2.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"