[build]
builder = "nixpacks"

[deploy]
startCommand = "python chronulus_mcp_server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
# CHRONULUS_API_KEY will be set in Railway dashboard